services:
  web:
    build: .
    command: uvicorn agent_backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ai_agent_db
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ai_agent_db

  test:
    build: .
    command: poetry run python scripts/test_db_connection.py
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
