site_name: AI Agent Framework
docs_dir: source
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: purple
    - scheme: slate
      primary: teal
      accent: lime

repo_name: SuperJackfruitLabs/agent-factory
repo_url: https://github.com/SuperJackfruitLabs/agent-factory

nav:
  - Home: index.md
  - API:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
  - Developer Guide:
    - Contributing: developer-guide/contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
